<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * One activation key. See the create_licenses_table migration for the model of
 * "effective expiry = MAX(expires_at)". Keys are generated by LicenseService,
 * never entered by hand.
 */
class License extends Model
{
    protected $fillable = [
        'key',
        'expires_at',
        'activated_at',
        'activated_by',
        'notes',
    ];

    protected $casts = [
        'expires_at' => 'datetime',
        'activated_at' => 'datetime',
    ];

    public function activatedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'activated_by');
    }
}
